[package]
name = "gc-arena-derive"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"
synstructure = "0.10"