language: rust
env:
  - RUSTFLAGS="-D warnings"
script:
  - cargo test --verbose --all
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly 
  allow_failures:
    - rust: nightly
