[package]
name = "luster"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "./gc-arena/",
    "./gc-sequence/",
]

[dependencies]
clap = "2.32"
num-traits = "0.2"
rustc-hash = "1.0"
rustyline = "3.0"
gc-arena = { path = "./gc-arena" }
gc-sequence = { path = "./gc-sequence" }
