[package]
name = "luster"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "./gc-arena/",
]

[dependencies]
rustc-hash = "1.0"
num-traits = "0.2"
gc-arena = { path = "./gc-arena" }

[dev-dependencies]
rustyline = "3.0.0"
