[package]
name = "luster"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]

[workspace]
members = [
    "./gc-arena/",
]

[dependencies]
failure = "0.1"
fnv = "1.0"
lazy_static = "1.0"
num-traits = "0.2"

gc-arena = { path = "./gc-arena" }