[package]
name = "piccolo"
version = "0.1.1"
authors = ["kyren <catherine@triplehex.dev>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/triplehex/piccolo"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0"
gc-arena = "0.3.1"
hashbrown = { version = "0.14", features = ["raw"] }
rand = { version = "0.8", features = ["small_rng"] }
rustc-hash = "1.1"
thiserror = "1.0"

[dev-dependencies]
clap = { version = "4.3", features = ["cargo"] }
rustyline = "11.0"
